### ISSUE TITLE
Crate publication

### ISSUE THREAD

**Issue by nappa85** [siefkenj/tsify#14]
As suggested in https://github.com/siefkenj/tsify/pull/9, this crate should be published to crates.io

Can you write somewhere a checklist of what's missing for publication, so anybody could help?

**Comment by Pistonight** [comment]
Looks like the original author is still active on github at least a couple month back, maybe we could contact them and ask to transfer the package ownership if they can no longer maintain it?

Meanwhile, this is what I put in `Cargo.toml` to use this fork
```toml
[patch.crates-io]
tsify = { git = "https://github.com/siefkenj/tsify" }
```

You can put a `ref = "<SHA>"` to lock to a commit
