### ISSUE TITLE
Bug: infinity f64 values becomes null in Javascript side

### ISSUE THREAD

**Issue by hillin** [siefkenj/tsify#48]
```toml
[dependencies]
tsify-next = { version = "0.5.4" }
serde = { version = "1.0.215", features = ["derive"] }
wasm-bindgen = "0.2.99"
```

```rust
#[derive(serde::Serialize, serde::Deserialize, tsify_next::Tsify)]
#[tsify(from_wasm_abi, into_wasm_abi)]
pub struct TestResult {
    pub value: f64,
}

#[wasm_bindgen]
pub fn test_negative_infinity() -> TestResult {
    TestResult {
        value: -f64::INFINITY,
    }
}

#[wasm_bindgen]
pub fn test_positive_infinity() -> TestResult {
    TestResult {
        value: f64::INFINITY,
    }
}
```

```js
test_negative_infinity().value  // null, should be -Infinity
test_positive_infinity().value  // null, should be Infinity
```

I've tried to decorate the `TestResult` with `#[wasm_bindgen]` only, it correctly returns `-Infinity` and `Infinity` respectively.
